language: R
cache: packages

# valgrind (disabled; takes too long, and errors don't affect the build)
#
# r_check_args: '--use-valgrind'
#
# addons:
#  apt:
#    packages:
#    - valgrind

r_github_packages:
  - jimhester/covr

before_install:
  - make NEWS

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      dist: trusty
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel

after_success:
  - export LC_ALL="C"
  - if [[ "${R_CODECOV}" ]]; then Rscript -e 'covr::codecov(line_exclusions = c("R/deprecated.R"))'; fi
